swagger: '2.0'
info:
  description: Sonat employee api
  version: "1.0.0"
  title: Sonat employee

basePath: /v1

consumes:
  - application/json

paths:
  /employees:
    get:
      tags:
        - Employee
      summary: Returns all employees
      operationId: getEmployees
      responses:
        200:
          description: A list of advisors
          schema:
            type: array
            items:
              $ref: '#/definitions/Employee'
    post:
      tags:
        - Employee
      summary: Add a new employee
      operationId: addEmployee
      parameters:
        - in: body
          name: employee
          required: true
          schema:
            $ref: '#/definitions/Employee'
      responses:
        201:
          $ref: '#/responses/CreateEmployeeResponse'
        400:
          description: Bad request
    put:
      tags:
        - Employee
      summary: Update an existing employee
      operationId: updateEmployee
      parameters:
        - in: body
          name: branch
          required: true
          schema:
            $ref: '#/definitions/Employee'
      responses:
        204:
          description: No content
        400:
          description: Bad request
        404:
          description: Employee not found

  '/employees/{id}':
    get:
      tags:
        - Employee
      summary: Find employee by ID
      description: Returns a single employee
      operationId: getEmployeeById
      parameters:
        - $ref: '#/parameters/idParam'
      responses:
        200:
          description: Employee
          schema:
            type: object
            items:
              $ref: '#/definitions/Employee'
        400:
          description: Invalid ID supplied
        404:
          description: Employee not found
      
    delete:
      tags:
        - Employee
      summary: Delete an employee
      operationId: deleteEmployee
      parameters:
        - $ref: '#/parameters/idParam'
      responses:
        204:
          description: No content
        400:
          description: Invalid ID supplied
        404:
          description: Employee not found
  
tags:
  - name: Employee
parameters:
  idParam:
    in: path
    name: id
    type: integer
    required: true
    x-example: 123

responses:
  CreateEmployeeResponse:
    description: Created an Advisor
    schema:
      $ref: '#/definitions/Id'

definitions:
  Employee:
      type: object
      required:
        - id
        - firstname
        - lastname
      properties:
        id:
          type: integer
          format: int64
        firstname:
          type: string
          example: Espen
        lastname:
          type: string
          example: Kvalheim
  Id:
    type: object
    required:
      - id
    properties:
      id:
        type: integer
        description: The id
        example: 123
