openapi: 3.0.0
info:
  description: Sonat employee api
  version: "1.0.0"
  title: Sonat employee
tags:
  - name: Employee

paths:
  /employees:
    get:
      tags:
        - Employee
      summary: Returns all employees
      operationId: getEmployees
      responses:
        200:
          description: successful
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Employee'

    post:
      tags:
        - Employee
      summary: Add a new employee
      operationId: addEmployee
      responses:
        201:
          description: Created
        400:
          description: Bad request
      requestBody:
        $ref: '#/components/requestBodies/Employee'

    put:
      tags:
        - Employee
      summary: Update an existing employee
      operationId: updateEmployee
      responses:
        204:
          description: No content
        400:
          description: Bad request
        404:
          description: Employee not found
      requestBody:
        $ref: '#/components/requestBodies/Employee'

  '/employees/{employeeId}':
    get:
      tags:
        - Employee
      summary: Find employee by ID
      description: Returns a single employee
      operationId: getEmployeeById
      parameters:
        - name: employeeId
          in: path
          description: ID of employee to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
        400:
          description: Invalid ID supplied
        404:
          description: Employee not found

    delete:
      tags:
        - Employee
      summary: Delete an employee
      operationId: deleteEmployee
      parameters:
        - name: employeeId
          in: path
          description: Employee id to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        204:
          description: No content
        400:
          description: Invalid ID supplied
        404:
          description: Employee not found

components:
  schemas:
    Employee:
      type: object
      required:
        - id
        - firstName
        - lastName
      properties:
        id:
          type: integer
          format: int64
        firstName:
          type: string
          example: Espen
        lastName:
          type: string
          example: Kvalheim
  requestBodies:
    Employee:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Employee'
      description: Employee object
      required: true
