openapi: "3.0.0"
info:
  title: "Test api"
  description: "Henter alle data om BCM laget vårt"
  version: "1.0"
  
paths:
  /runners:
    get:
      tags:
        - Runners
      summary: Henter alle løpere
      operationId: getRunners
      responses:
        200:
          description: Suksess
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Runner'
              
  /runners/{id}:
    get:
      tags:
        - Runners
      summary: Henter en spesifikk løper
      operationId: getRunner
      parameters: 
        - in: path
          name: id
          description: id på løper
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Suksess
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Runner'
              
components:
  schemas:
    Runner:
      type: object
      required:
        - id
        - firstName
        - speed
      properties:
        id:
          type: integer
          format: int64
        firstName:
          type: string
          example: Espen
        speed:
          type: integer
          format: int64
          example: 10
